version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.cloudbees.jenkins.plugins*
    versions:
    - ">= 0"
  - dependency-name: io.jenkins.docker:docker-plugin
    versions:
    - ">= 0"
  - dependency-name: io.jenkins.plugins*
    versions:
    - ">= 0"
  - dependency-name: org.csanchez.jenkins.plugins*
    versions:
    - ">= 0"
  - dependency-name: org.jenkins-ci.main:jenkins-core
    versions:
    - ">= 0"
  - dependency-name: org.jenkins-ci.plugins*
    versions:
    - ">= 0"
  - dependency-name: org.jenkinsci.plugins*
    versions:
    - ">= 0"
  - dependency-name: com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.jenkins-ci.main:maven-plugin
    versions:
    - "3.9"
  - dependency-name: io.netty:netty-codec-http
    versions:
    - 4.1.58.Final
  - dependency-name: com.datapipe.jenkins.plugins:hashicorp-vault-plugin
    versions:
    - 3.7.0
  - dependency-name: com.github.docker-java:docker-java
    versions:
    - 3.2.7
  - dependency-name: io.netty:netty-handler
    versions:
    - 4.1.45.Final
  - dependency-name: org.apache.maven:maven-model
    versions:
    - 3.6.3
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.10.0
